openapi: 3.0.4
info:
  title: Timezone Lookup
  description: >-
    Timezone Lookup is a simple tool for looking up timezone data. It returns
    the timezone name, offset, and more.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.0
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
  - url: https://api.apiverve.com/
paths:
  /v1/timezonelookup:
    get:
      summary: Lookup Timezone by City
      description: Lookup timezone data based on the city name
      operationId: timezonelookup
      parameters:
        - name: city
          in: query
          schema:
            type: string
          required: true
          description: The city name for which you want to get the data (e.g., Harare)
          example: Harare
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: object
                    description: data
              example:
                status: ok
                error: null
                data:
                  timezone: Africa/Harare
                  timezone_offset: 120
                  date: '2025-12-17'
                  time: '00:30'
                  time24: '00:30:23'
                  time12: 12:30:23 AM
                  day: Wednesday
                  month: December
                  year: '2025'
                  unix: '1765924223'
                  dst: false
                  dst_start: '2025-12-17 00:30:23'
                  dst_end: '2025-12-17 00:30:23'
                  dst_name: CAT
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occurred, try again later
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
  - api_key: []
